[package]
name = "hyper-rustls"
version = "0.4.0"
authors = ["Joseph Birr-Pixton <jpixton@gmail.com>"]
license = "Apache-2.0/ISC/MIT"
readme = "README.md"
description = "Rustls+hyper integration for pure rust HTTPS"
homepage = "https://github.com/ctz/hyper-rustls"
repository = "https://github.com/ctz/hyper-rustls"

[features]
default = ["client", "server"]
client = ["webpki-roots"]
server = []

[dependencies]
webpki-roots = { version = "0.7.0", optional = true }
rustls = "0.5.6"

[dependencies.hyper]
version = "0.10"
default-features = false

[dev-dependencies]
log = "0.3"
env_logger = "0.3"
